---
title: "Global Fishing Watch Basics"
output: html_document
---

# Global Fishing Watch Basics

This section covers the basics of Global Fishing Watch data including the types of data available and cautions for using the data.  

## Types of Data

The Global Fishing Watch (GFW) primary dataset is compiled from Automated Identification System (AIS) data. AIS was originally designed for ship-to-ship communication to help avoid collisions and vessels transmit a lot of information within an AIS message including vessel identity, position, and speed. AIS messages are received by other ships as well as being picked up by terrestrial and satellite receivers. These data are publicly available. More detailed information on AIS and the challenges and opportunities for using AIS to map and analyze fishing activity are presented in the 2019 [Global Atlas of AIS-based Fishing Activity](http://www.fao.org/documents/card/en/c/ca7012en).   

The GFW database also has Vessel Monitoring System (VMS) data for a number of countries. VMS broadcasts vessel location to satellite and terrestrial receivers, which are then relayed to shore-based fishery monitoring centers. Unlike AIS, VMS data are not publicly available and the GFW database only contains data for countries who have agreed to share them. The [BigQuery Reference Table](https://docs.google.com/spreadsheets/d/1B8Q04rzWRdffty2gVBlHiBDS9DYZLdW8J-4B3xja5ws/edit#gid=0) contains the most up to date list of available country VMS data.   

GFW is also working on additional datasets composed of vessel detections derived from global satellite imagery collections including Synthetic Aperture Radar (SAR) and Visible Infrared Imaging Radiometer Suite (VIIRS). SAR produces high resolution images which are derived from two European Space Agency satellites: S1A and S1B of Sentinel-1 mission. The VIIRS dataset uses a nightly VIIRS Boat Detection (VBD) dataset produced by NOAA's Earth Observation Group. The VBD reports the location of boats detected based on light using a sensor onboard the Suomi National Polar-orbiting Partnership and NOAA-20 weather satellites. The methods underlying production of the VBD dataset are described in [Elvidge et al. 2015](https://www.mdpi.com/2072-4292/7/3/3020). These datasets have been used together and combined with other high-resolution optical imagery to illuminate vessels that don’t broadcast AIS, also known as dark targets. Both of these datasets can detect vessels but neither show continuous vessel tracks. GFW is developing more information and examples of how to use these data which will be updated on the [GitHub Wiki](https://github.com/GlobalFishingWatch/bigquery-documentation-wf827/wiki) page. If you can't view the page you can request access to the GFW GitHub repository from Tyler Clavelle.   

## Available Data

The GFW AIS dataset includes three main types of information about vessels: attributes (such as length, tonnage, flag, and gear type), positions (in WGS84), and activities (like encounters, loitering, port visits, and fishing). Data are available from 2012 -  present. AIS coverage has increased overtime and is generally considered good from 2016 onward. Most of the tables with vessel information are related through the source specific vessel id (ssvid). For AIS data, the ssvid corresponds to the vessel’s Maritime Mobile Service Identity (MMSI).  

Country VMS datasets provide reliable vessel tracking with low risks of tampering or transmission gaps since VMS devices generally broadcast at fixed rates and many countries impose strict requirements on VMS use with hefty fines for violations. When available, VMS data can complement AIS data, particularly in regions where AIS reception is poor, allowing for a greater understanding of fishing activity. Years of available data and level of metadata for VMS varies by country and approval to use the data is almost always required. A description and date range for the various country VMS datasets is provided on the [GFW VMS Wiki](https://github.com/GlobalFishingWatch/bigquery-documentation-wf827/wiki/VMS) page. If you are interested in using VMS data in your research please reach out to Tyler Clavelle at GFW.    

The SAR detections data are from around October, 2014 - present and are updated intermittently. Imagery availability increases along the data acquisition timeframe, especially from mid-2016 on. However, SAR detections only cover nearshore regions and most offshore areas do not have any detection data. VIIRS data is available from 2016 - present and is updated periodically.  

## Data Caution

While GFW data are a powerful tool for analysis, there are a number of issues with AIS data which are important to consider. First, AIS has potential issues with reception quality, spoofing, and bad data. There are a number of situations where AIS messages might be broadcasted but not recorded by satellites. In order to receive a message, satellites must be overhead and terrestrial satellites will only record messages within line-of-sight (approximately 10 -100 nautical miles). AIS devices also vary in strength and high densities of vessels can interfere with each other preventing satellites from recording all vessel messages. There are two types of spoofing to be aware of: identity spoofing and location spoofing. Identity spoofing occurs when two or more vessels are simultaneously broadcasting the same vessel identification number, while location spoofing, or offsetting, refers to manipulation of the vessel’s AIS position to obscure the true location. Finally, bad data may show fishing vessel tracks in places that don’t make sense, like on land.   

There are a number of solutions to deal with these AIS problems. To verify reception quality, it may be helpful to check the quality of coverage for your research area using `world-fishing-827.gfw_research.reception_quality_quarterdegree_vYYYYMMDD`. Vessel info tables (such as `world-fishing-827.gfw_research.vi_ssvid_byyear_vYYYYMMDD`) can be filtered to exclude potential spoofing or offsetting vessels using the activity record. It is also common to filter for vessel segments with more than 10 positions that are not overlapping and short. Examples of common noise filters to deal with these types of issues can be found in the example queries on the [GFW GitHub](https://github.com/GlobalFishingWatch/bigquery-documentation-wf827/tree/master/queries/examples). The best way to deal with potentially bad data is to be diligent in checking, visualizing, and critically evaluating the data. GFW is constantly improving their pipeline process and vessel lists with help from research partners. Any bad data or possible data issues can be reported to the GFW team through the emlab-gfw slack channel. Posts should tag Tyler Clavelle on the GFW team. 

It is also important to consider how AIS has changed since it was first adopted, especially if using AIS data for time series studies. Both AIS reception quality and use of AIS have improved and grown in recent years. Time series studies should consider ways to deal with this, either by restricting analyses to only those vessels broadcasting at the beginning of the study time period or restricting analyses to 2016 onwards. 

While GFW data is accurate, it relies on the accuracy and transparency of public fisheries data. It is important to critically analyze the data before using them and to understand what can and can’t be said. For example best practice is to use terms like apparent fishing effort rather than fishing effort, and encounters and loitering events instead of transshipment events. Further, it’s important to recognize that AIS data only covers a fraction of the world’s fishing fleets. The [Global Atlas of AIS-based Fishing Activity](http://www.fao.org/documents/card/en/c/ca7012en) describes in more detail which fraction of the global fishing fleet is believed to be represented in the existing AIS data.  